### PR TITLE
fix getDevPackage() to work for windows

### LINKED ISSUE #4: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
I'm seeing the following environment
windows: 7
node: v4.2.6
npm: 2.14.12
npm-autolink: 0.3.1

I'm seeing the following crashes

> > npm-autolink list

<--- Last few GCs --->

   29590 ms: Scavenge 1397.9 (1457.9) -> 1397.9 (1457.9) MB, 2.6 / 0 ms (+ 107.0 ms in 1 steps since last GC) [allocatio
n failure] [incremental marking delaying mark-sweep].
   30454 ms: Mark-sweep 1397.9 (1457.9) -> 1397.8 (1457.9) MB, 864.0 / 3 ms (+ 201.0 ms in 12 steps since start of marki
ng, biggest step 107.0 ms) [last resort gc].
   31347 ms: Mark-sweep 1397.8 (1457.9) -> 1397.8 (1457.9) MB, 893.0 / 3 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003FE5AFB4639 <JS Object>
    2: normalize [path.js:~182] [pc=0000021755EFBA52](this=00000243B1443AC9 <an Object with map 00000204B6E0B1C1>,path=
000001982C514529 <String[13]: E:\.autolink)
    3: join [path.js:~217] [pc=0000021755FA1554](this=00000243B1443AC9 <an Object with map 00000204B6E0B1C1)
    4: arguments adaptor frame: 2->0
    5: getDevPackagesFromPath(aka getDevPackagesFromPath) [C:\Users\pgreen\AppDat...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

> > npm-autolink matches

<--- Last few GCs --->

   26428 ms: Scavenge 1404.3 (1457.9) -> 1404.3 (1457.9) MB, 6.2 / 0 ms (+ 25.0 ms in 1 steps since last GC) [allocation
 failure] [incremental marking delaying mark-sweep].
   27498 ms: Mark-sweep 1404.3 (1457.9) -> 1404.3 (1457.9) MB, 1070.2 / 3 ms (+ 867.0 ms in 3387 steps since start of ma
rking, biggest step 25.0 ms) [last resort gc].
   28570 ms: Mark-sweep 1404.3 (1457.9) -> 1404.2 (1457.9) MB, 1071.8 / 3 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003B6EF3B4639 <JS Object>
    2: normalize [path.js:~182] [pc=00000315BCAA1C32](this=0000037324A44271 <an Object with map 0000024202D0B1C1>,path=
0000037324AD0EE9 <String[13]: E:\.autolink)
    3: join [path.js:~217] [pc=00000315BCAA4034](this=0000037324A44271 <an Object with map 0000024202D0B1C1)
    4: arguments adaptor frame: 2->0
    5: getDevPackagesFromPath(aka getDevPackagesFromPath) [C:\Users\pgreen\AppDat...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### PR DESCRIPTION
**Pull request by phillipgreenii**
Fix directory search on windows (fixes #4)

### CODE REVIEW

**Comment by phillipgreenii** [comment]
Any chance of this getting merged and redeployed to NPM?

**Comment by GTrebaol** [comment]
I doubt it :/

**Comment by adogor** [comment]
Hi,
Sorry for the delay.
I will do extra tests today and merge.

**Comment by phillipgreenii** [comment]
Thank you!

**Pull request merged**
